### ISSUE TITLE
uBO / AdGuard CSS suplement

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishRSSFilters#58]
### Moja konfiguracja
**Przeglądarka internetowa:** 

**System operacyjny:** Windows 7

**Bloker:** uBO

**Używane filtry:**
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry RSS
4.

### Link bezpośredni (opcjonalny)

`https://github.com/PolishFiltersTeam/PolishRSSFilters/`

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

```css
wsqn.pl#$#.extralight-border { border: none !important; }
```

https://github.com/PolishFiltersTeam/PolishRSSFilters/blob/b58fa54a3857d14766ecd60c81fd08a0a66d2b4b/polish_rss_filters/specyficzne_ukrywajace.txt#L173

I problem potencjalny w AdBlock / Adblock Plus lub magiach Privoxy.

**Comment by krystian3w** [comment]
@hawkeye116477  da się tu wyłączyć też by bot nie zamykał tematów?

**Comment by hawkeye116477** [comment]
@krystian3w W `https://github.com/PolishFiltersTeam/PolishRSSFilters/blob/master/.github/probot.js` musisz zmienić.

**Comment by krystian3w** [comment]
No to wyłączyłem komentarzem.
